### ISSUE TITLE
Calling a C# method from JS

### ISSUE THREAD

**Issue by nesk** [SupinePandora43/UltralightNet#24] opened 2021-06-22 22:05 UTC
With Ultralight it's possible [to call a C function from JS](https://docs.ultralig.ht/docs/calling-a-c-function-from-js), is it possible to call a C# method from JS with UltralightNet?

**Comment by SupinePandora43** [comment] 2021-06-23 11:45
*`function`* is just a pointer.
in c#/.NET you can get it using two ways:
1. `Marshal.GetFunctionPointerForDelegate`
2. `&FuncName` (`[UnmanagedCallersOnly(CallConvs = new Type[]{typeof(CallConvCdecl)}]`)

**Comment by nesk** [comment] 2021-06-23 11:59
`Marshal.GetFunctionPointerForDelegate` is what I want here, but how do I pass the pointer to Ultralight? I only see bindings for JavaScriptCore [in UltralightSharp](https://github.com/SupinePandora43/UltralightNet/blob/9fe85f2a55aa26411b8356c8512c44b1813526f1/UltralightSharp/JavaScriptCore.cs#L161-L165), not in UltralightNet. For example, how can I call [the `JSObjectMakeFunctionWithCallback` function](https://github.com/ultralight-ux/Ultralight-API/blob/a221b7f8654f04dff1df9dd40b0cc9b4d746b03e/JavaScriptCore/JSObjectRef.h#L515-L523)?

**Comment by SupinePandora43** [comment] 2021-06-24 06:14
UltralightNet doesn't have any JSCore bindings **yet**

**Comment by nesk** [comment] 2021-06-24 11:20
That's what I thought, thank you 🙂

**Comment by SupinePandora43** [comment] 2021-07-12 16:02
duplicate of #11 i guess

**Closed by SupinePandora43** 2021-07-12 16:02 UTC
